# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0c82d6a72713cc6352c73eb495681ad8871da53998e86dc772e09c0872d9ebeb4b1184ff1ccbe0a245365373830cd530f805a3ac93e99e854dc18473257a222

test:
  secret_key_base: 1690792e759113e7103132a021f841f3b58b97b665c83873c0482f5f62127b170ed22ae4ff5888ee948ea7e4ca0b978a39e511668f0ed02231feadb82491bb0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
